Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
build/ansible/DOCKERFILES/Dockerfile-work.j2

Add rsync as required asked for here: https://github.com/cytopia/devilbox/issues/343

Adding rsync as a standard tool to all container

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
build/ansible/DOCKERFILES/Dockerfile-work.j2

* Refs: https://github.com/devilbox/docker-php-fpm/issues/36

Refs #36: Adding ZSH shell

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
build/ansible/DOCKERFILES/Dockerfile-work.j2

Fixes: https://github.com/cytopia/devilbox/issues/369

Add Tool: unzip

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
build/ansible/DOCKERFILES/Dockerfile-work.j2

Fixes https://github.com/cytopia/devilbox/issues/376

Add graphviz to all worker images

---

Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
build/ansible/group_vars/all.yml

* Refs: https://github.com/cytopia/devilbox/issues/384

Add drush7, drush8 and drush9 as separate binaries

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
README.md
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all.yml

* Adding `jq` as per request: https://github.com/cytopia/devilbox/issues/154

Add tool: jq

---

.travis.yml

This PR ensures that cron-triggered tags are actually pushed.
Related issues: https://github.com/travis-ci/travis-ci/issues/8146

Ensure Travis-CI recognizes when being run as cronjob

---

Dockerfiles/base/Dockerfile-7.3
Dockerfiles/mods/Dockerfile-7.3
README.md
build/ansible/DOCKERFILES/Dockerfile-base.j2
build/ansible/group_vars/all.yml

WIP: Use latest stable PHP 7.3 base image

---

Dockerfiles/mods/Dockerfile-5.2
Dockerfiles/mods/Dockerfile-5.3
Dockerfiles/mods/Dockerfile-5.4
Dockerfiles/mods/Dockerfile-5.5
Dockerfiles/mods/Dockerfile-5.6
Dockerfiles/mods/Dockerfile-7.0
Dockerfiles/mods/Dockerfile-7.1
Dockerfiles/mods/Dockerfile-7.2
Dockerfiles/mods/Dockerfile-7.3
Dockerfiles/mods/Dockerfile-7.4
Dockerfiles/work/data/bash-devilbox
build/ansible/group_vars/all.yml

* Fixes install of memcached
* Updates available tools in bash logo: https://github.com/cytopia/devilbox/issues/432

Release 0.57

---

Dockerfiles/prod/data/docker-entrypoint.sh
Dockerfiles/work/data/docker-entrypoint.sh

Prefix variables to prevent name collisions

Release v0.61

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
README.md
build/ansible/group_vars/all.yml
tests/base/04-test-run_nginx.sh
tests/prod/05-test-env-forward_ports_to_localhost.sh
tests/prod/06-test-mount-custom_ini.sh
tests/prod/07-test-mount-custom_fpm_conf.sh
tests/work/01-test-env-mysqldump-secure.sh

This PR bakes [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) into the images.
* Refs: https://github.com/cytopia/devilbox/issues/467

Release 0.68

---

.travis.yml
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
build/ansible/group_vars/all.yml
tests/base/04-test-run_nginx.sh
tests/prod/05-test-env-forward_ports_to_localhost.sh
tests/prod/06-test-mount-custom_ini.sh
tests/prod/07-test-mount-custom_fpm_conf.sh
tests/work/01-test-env-mysqldump-secure.sh

This is a bugfix release to address various CI issues and ensures `deployer` works on all versions again.

Release 0.70

---

Dockerfiles/mods/Dockerfile-7.4
README.md
build/ansible/group_vars/all.yml

Remove imap from PHP 7.4 due to build errors

Remove imap from PHP 7.4 due to build errors

---

Dockerfiles/mods/Dockerfile-5.2
Dockerfiles/mods/Dockerfile-5.3
Dockerfiles/mods/Dockerfile-5.4
Dockerfiles/mods/Dockerfile-5.5
Dockerfiles/mods/Dockerfile-5.6
Dockerfiles/mods/Dockerfile-7.0
Dockerfiles/mods/Dockerfile-7.1
Dockerfiles/mods/Dockerfile-7.2
Dockerfiles/mods/Dockerfile-7.3
Dockerfiles/mods/Dockerfile-7.4
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
build/ansible/DOCKERFILES/Dockerfile-mods.j2
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all.yml

* Ensure that PHP FFI is enabled by default.
* Add `zip` binary: https://github.com/cytopia/devilbox/issues/471

Release 0.72

---

Dockerfiles/mods/Dockerfile-7.3
build/ansible/group_vars/all.yml

Use latest xdebug version for PHP 7.3

Fixes #75 Use latest xdebug version for PHP 7.3

---

Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all.yml

* Refs: https://github.com/cytopia/devilbox/issues/493

Use QT-patched version of wkhtmltopdf

---

Dockerfiles/mods/Dockerfile-7.3
build/ansible/group_vars/all.yml

* https://xdebug.org/#2019_03_06

Use PHP Xdebug 2.7 Release

---

Dockerfiles/mods/Dockerfile-5.3
Dockerfiles/mods/Dockerfile-5.4
Dockerfiles/mods/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
build/ansible/group_vars/all/mods.yml
build/ansible/group_vars/all/work.yml

* Fixes https://github.com/devilbox/docker-php-fpm/issues/109 (Add Laravel Lumen)
* Refs: https://github.com/cytopia/devilbox/issues/559 (Laravel Lumen)
* Refs: https://github.com/cytopia/devilbox/issues/557 (Angular CLI)

Release 0.84

---

Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
build/ansible/group_vars/all/work.yml

 Release 0.95

---

Dockerfiles/prod/data/docker-entrypoint.d/301-postfix.sh
Dockerfiles/prod/data/docker-entrypoint.sh
Dockerfiles/prod/data/postfix.sh
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
Dockerfiles/work/data/docker-entrypoint.sh
README.md
build/ansible/group_vars/all/work.yml
tests/prod/04-test-env-enable_mail.sh

* Allow to start postfix without Email catch-all
* Add `-o` option to `mhsendmail`
* Refs: https://github.com/cytopia/devilbox/issues/642
* Refs: https://github.com/cytopia/devilbox/issues/614
* Fixes #105

Release v0.98

---

Dockerfiles/mods/Dockerfile-7.4
Dockerfiles/mods/Dockerfile-8.0
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
Makefile
README.md
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all/mods.yml
build/ansible/group_vars/all/work.yml

* Refs https://github.com/cytopia/devilbox/issues/615 Add `phpmd` binary

Add phpmd binary

---

CHANGELOG.md
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
build/ansible/group_vars/all/work.yml

- [#144](https://github.com/devilbox/docker-php-fpm/issues/144) Added CHANGELOG
- [#123](https://github.com/devilbox/docker-php-fpm/issues/123) Added Dart Sass and removed Ruby Sass
- Replace [scss-lint](https://github.com/sds/scss-lint) with [stylelint](https://github.com/stylelint/stylelint)

Release 0.102

---

CHANGELOG.md
Dockerfiles/mods/Dockerfile-7.0
build/ansible/group_vars/all/mods.yml

- Fix xdebug install for PHP 7.0

Release 0.104

---

CHANGELOG.md
Dockerfiles/mods/Dockerfile-7.1
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all/mods.yml
build/ansible/group_vars/all/work.yml

- Fix pdo_sqlsrv install for PHP 7.1
- Fix composer memory issues during install
- `phalcon` binary for PHP 7.3 and 7.4
* https://github.com/cytopia/devilbox/issues/670

Release 0.105

---

CHANGELOG.md
Dockerfiles/mods/Dockerfile-5.2
Dockerfiles/mods/Dockerfile-5.3
Dockerfiles/mods/Dockerfile-5.4
Dockerfiles/mods/Dockerfile-5.5
Dockerfiles/mods/Dockerfile-5.6
Dockerfiles/mods/Dockerfile-7.0
Dockerfiles/mods/Dockerfile-7.1
Dockerfiles/mods/Dockerfile-7.2
Dockerfiles/mods/Dockerfile-7.3
Dockerfiles/mods/Dockerfile-7.4
Dockerfiles/mods/Dockerfile-8.0
README.md
build/ansible/group_vars/all/mods.yml

- Fix build of PHP-FPM 7.4 snmp module
- Fix build of PHP-FPM 8.0 uploadprogress module
* Refs: https://github.com/devilbox/docker-php-fpm/issues/156

Release 0.106

---

CHANGELOG.md
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
build/ansible/group_vars/all/work.yml

Fixes download for drupal console
- [169](https://github.com/devilbox/docker-php-fpm/issues/169) Fixes download for drupal console
- Fixes laravel installer for PHP 7.2

Release v0.110

---

CHANGELOG.md
Dockerfiles/mods/Dockerfile-8.0
README.md
build/ansible/group_vars/all/mods.yml

Release v0.111

---

.github/workflows/php-ci.yml
.github/workflows/php-nightly.yml
CHANGELOG.md
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
build/ansible/DOCKERFILES/Dockerfile-work.j2
build/ansible/group_vars/all/work.yml

- Fixed `drupal` (drupal console launcher) for PHP 5.5, 5.6, 7.0 and 7.1

Release 0.119

---

CHANGELOG.md
Dockerfiles/base/data/docker-entrypoint.d/101-uid-gid.sh
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
Dockerfiles/work/Dockerfile-8.1
Dockerfiles/work/Dockerfile-8.2
build/ansible/group_vars/all/work.yml

Adresses https://github.com/cytopia/devilbox/issues/499

Release 0.141

---

.ansible/group_vars/all/work.yml
CHANGELOG.md
Dockerfiles/work/Dockerfile-5.2
Dockerfiles/work/Dockerfile-5.3
Dockerfiles/work/Dockerfile-5.4
Dockerfiles/work/Dockerfile-5.5
Dockerfiles/work/Dockerfile-5.6
Dockerfiles/work/Dockerfile-7.0
Dockerfiles/work/Dockerfile-7.1
Dockerfiles/work/Dockerfile-7.2
Dockerfiles/work/Dockerfile-7.3
Dockerfiles/work/Dockerfile-7.4
Dockerfiles/work/Dockerfile-8.0
Dockerfiles/work/Dockerfile-8.1
Dockerfiles/work/Dockerfile-8.2
doc/available-tools.md
php_tools/net-tools/README.md
php_tools/net-tools/install.yml
php_tools/net-tools/options.yml

Release 0.149
